### To know grant-all-privileges 
#### https://www.oracletutorial.com/oracle-administration/oracle-grant-all-privileges-to-a-user/


TRUNCATE TABLE students;

CREATE TABLE students (
    id NUMBER (4) NOT NULL UNIQUE,
	name VARCHAR(128) NULL,

);


CREATE TABLE users (

	id NUMBER (4) NOT NULL PRIMARY KEY,
	name VARCHAR(128) NULL,
	active_date DATE DEFAULT SYSDATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE cities (

	id NUMBER (4) NOT NULL PRIMARY KEY,
	name VARCHAR(128) NULL,
	code VARCHAR(128) NULL,
	active_date DATE DEFAULT SYSDATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



ALTER TABLE students;
MODIFY id NOT NULL PRIMARY KEY;

ALTER TABLE students
ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE students
ADD updated_at TIMESTAMP DEFAULT NOW();


ALTER TABLE students
ADD active_date DATE DEFAULT SYSDATE NOT NULL;



INSERT INTO students (name) VALUES  ('Saim');
INSERT INTO students (name) VALUES  ('Ringku');
INSERT INTO students (name) VALUES  ('Jibran');
INSERT INTO students (name) VALUES  ('Nipa');
INSERT INTO students (name) VALUES  ('Nico');


1=payment, 2=receipt, 3=journal, 4=contra	
INSERT INTO RELACCOUNTS (name) VALUES  ('PHS');
INSERT INTO RELACCOUNTS (name) VALUES  ('FDR');



select * from students;

select id, name, TO_CHAR(active_date,'MM-DD-YYYY') as created_at from students;


select id, name, TO_CHAR(created_at,'dd/mm/yyyy') as created_at from students;

select id, name, TO_CHAR(SYSDATE, 'MM-DD-YYYY HH12:MI:SS') AS today  from students;

select id, name, TO_CHAR(CURRENT_DATE, 'DD-MON-YYYY HH:MI:SS') AS today  from students;

select id, name, TO_CHAR(sysdate,'Day, ddth Month, yyyy') as today from students;






CREATE TABLE SUPPLEMENTS (

	id NUMBER (20) NOT NULL PRIMARY KEY,
	code NVARCHAR2(128) NULL,
	name NVARCHAR2(128) NULL,
	status NUMBER (1) DEFAULT 1,
	activedate DATE DEFAULT SYSDATE NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




CREATE SEQUENCE AI_SEQ_SUPPLEMENTS START WITH 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999;

CREATE OR REPLACE TRIGGER SUPPLEMENTS_AUTO_INCREMENT 
BEFORE INSERT ON SUPPLEMENTS 
FOR EACH ROW

BEGIN
  SELECT AI_SEQ_SUPPLEMENTS.NEXTVAL INTO   :NEW.ID FROM   dual;
END;

CREATE OR REPLACE TRIGGER BIN_BUP_SUPPLEMENTS_TR
BEFORE INSERT OR UPDATE ON SUPPLEMENTS FOR EACH ROW

BEGIN
  IF INSERTING THEN
    :NEW.CODE := TO_CHAR(SYSDATE,'MM') + TO_CHAR(SYSDATE,'YYYY') + AI_SEQ_SUPPLEMENTS.NEXTVAL;
  END IF;

  IF UPDATING THEN
    :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
  END IF;

END;

